### ISSUE TITLE
Fail on bulding some datasets

### ISSUE THREAD

**Issue by bagustris** [Neclow/SERAB#1]
Hi @Neclow, 

I failed to build AESDD dataset using your recipe

```bash
(serab) bagus@pc-omen:aesdd$ tfds build                                                                                                                                                  
2022-11-16 16:56:17.762030: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-16 16:56:17.850300: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-11-16 16:56:18.243007: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/bagus/miniconda3/envs/serab/lib/:/var/lib/docker/overlay2/b2c6c735b823297983b5e6d11c64147f8307a4ece255c7f36276dd9066cf8142/diff/usr/lib/x86_64-linux-gnu/
2022-11-16 16:56:18.243052: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/bagus/miniconda3/envs/serab/lib/:/var/lib/docker/overlay2/b2c6c735b823297983b5e6d11c64147f8307a4ece255c7f36276dd9066cf8142/diff/usr/lib/x86_64-linux-gnu/
2022-11-16 16:56:18.243059: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2022-11-16 16:56:19.449061: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-11-16 16:56:19.454121: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/bagus/miniconda3/envs/serab/lib/:/var/lib/docker/overlay2/b2c6c735b823297983b5e6d11c64147f8307a4ece255c7f36276dd9066cf8142/diff/usr/lib/x86_64-linux-gnu/
2022-11-16 16:56:19.454137: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1934] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
INFO[build.py]: Loading dataset  from path: /home/bagus/github/SERAB/tensorflow_datasets/aesdd/aesdd.py
2022-11-16 16:56:19.457076: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "NOT_FOUND: Could not locate the credentials file.". Retrieving token from GCE failed with "FAILED_PRECONDITION: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: metadata".
INFO[build.py]: download_and_prepare for dataset aesdd/1.0.0...
INFO[dataset_builder.py]: Generating dataset aesdd (/home/bagus/tensorflow_datasets/aesdd/1.0.0)
Downloading and preparing dataset Unknown size (download: Unknown size, generated: Unknown size, total: Unknown size) to /home/bagus/tensorflow_datasets/aesdd/1.0.0...
INFO[download_manager.py]: Reusing extraction of /home/bagus/tensorflow_datasets/downloads/manual/Acted Emotional Speech Dynamic Database.zip at /home/bagus/tensorflow_datasets/downloads/extracted/ZIP.Acted Emotional Speech Dynamic Database.zip.
Extraction completed...: 0 file [00:00, ? file/s]
Generating splits...:   0%|                                       Traceback (most recent call last):                                                          | 0/3 [00:00<?, ? splits/s]
  File "/home/bagus/miniconda3/envs/serab/bin/tfds", line 8, in <module>
    sys.exit(launch_cli())
  File "/home/bagus/miniconda3/envs/serab/lib/python3.8/site-packages/tensorflow_datasets/scripts/cli/main.py", line 126, in launch_cli
    app.run(main, flags_parser=_parse_flags)
  File "/home/bagus/miniconda3/envs/serab/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/bagus/miniconda3/envs/serab/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/bagus/miniconda3/envs/serab/lib/python3.8/site-packages/tensorflow_datasets/scripts/cli/main.py", line 121, in main
    args.subparser_fn(args)
  File "/home/bagus/miniconda3/envs/serab/lib/python3.8/site-packages/tensorflow_datasets/scripts/cli/build.py", line 199, in _build_datasets
    _download_and_prepare(args, builder)
  File "/home/bagus/miniconda3/envs/serab/lib/python3.8/site-packages/tensorflow_datasets/scripts/cli/build.py", line 355, in _download_and_prepare
    builder.download_and_prepare(
  File "/home/bagus/miniconda3/envs/serab/lib/python3.8/site-packages/tensorflow_datasets/core/dataset_builder.py", line 439, in download_and_prepare
    self._download_and_prepare(
  File "/home/bagus/miniconda3/envs/serab/lib/python3.8/site-packages/tensorflow_datasets/core/dataset_builder.py", line 1155, in _download_and_prepare
    split_info_futures = [
  File "/home/bagus/miniconda3/envs/serab/lib/python3.8/site-packages/tensorflow_datasets/core/dataset_builder.py", line 1156, in <listcomp>
    split_builder.submit_split_generation(  # pylint: disable=g-complex-comprehension
  File "/home/bagus/miniconda3/envs/serab/lib/python3.8/site-packages/tensorflow_datasets/core/split_builder.py", line 291, in submit_split_generation
    return self._build_from_generator(**build_kwargs)
  File "/home/bagus/miniconda3/envs/serab/lib/python3.8/site-packages/tensorflow_datasets/core/split_builder.py", line 361, in _build_from_generator
    utils.reraise(e, prefix=f'Failed to encode example:\n{example}\n')
  File "/home/bagus/miniconda3/envs/serab/lib/python3.8/site-packages/tensorflow_datasets/core/split_builder.py", line 359, in _build_from_generator
    example = self._features.encode_example(example)
  File "/home/bagus/miniconda3/envs/serab/lib/python3.8/site-packages/tensorflow_datasets/core/features/features_dict.py", line 198, in encode_example
    utils.reraise(
  File "/home/bagus/miniconda3/envs/serab/lib/python3.8/site-packages/tensorflow_datasets/core/features/features_dict.py", line 196, in encode_example
    example[k] = feature.encode_example(example_value)
  File "/home/bagus/miniconda3/envs/serab/lib/python3.8/site-packages/tensorflow_datasets/core/features/audio_feature.py", line 97, in encode_example
    utils.reraise(e, prefix=f'Error for {filename}: ')
  File "/home/bagus/miniconda3/envs/serab/lib/python3.8/site-packages/tensorflow_datasets/core/features/audio_feature.py", line 95, in encode_example
    return self._encode_file(audio_f, file_format)
  File "/home/bagus/miniconda3/envs/serab/lib/python3.8/site-packages/tensorflow_datasets/core/features/audio_feature.py", line 75, in _encode_file
    audio_segment = lazy_imports_lib.lazy_imports.pydub.AudioSegment.from_file(
  File "/home/bagus/miniconda3/envs/serab/lib/python3.8/site-packages/pydub/audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "/home/bagus/miniconda3/envs/serab/lib/python3.8/site-packages/pydub/utils.py", line 279, in mediainfo_json
    info = json.loads(output)
  File "/home/bagus/miniconda3/envs/serab/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/bagus/miniconda3/envs/serab/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/bagus/miniconda3/envs/serab/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Failed to encode example:
{'audio': '/home/bagus/tensorflow_datasets/downloads/extracted/ZIP.Acted Emotional Speech Dynamic Database.zip/Acted Emotional Speech Dynamic Database/anger/a16 (2).wav', 'label': 'anger', 'speaker_id': '2'}
In <Audio> with name "audio":
Error for /home/bagus/tensorflow_datasets/downloads/extracted/ZIP.Acted Emotional Speech Dynamic Database.zip/Acted Emotional Speech Dynamic Database/anger/a16 (2).wav: Expecting value: line 1 column 1 (char 0)
```

I am wondering what tensorflow version you used to build the dataset. Mine used TF 2.10. Also, the requirement of tensorflow is not stated in `serab.yaml`

**Comment by Neclow** [comment]
Hi @bagustris 

SERAB does not use tensorflow. It requires ```tensorflow-datasets==4.3.0``` and ```tensorflow-hub==0.12.0``` to load datasets and pretrained models, but its DL framework is ```pytorch==1.9.0```.

I just checked using the demo notebook and had no problem with AESDD (link to the Colab notebook: https://colab.research.google.com/drive/1LoLQxMxJ9tEdSvRwofhV1bTeY_YHV-Wx?usp=sharing).

Is your error only related to AESDD, or do you end up with the same error with other datasets?

I hope this can be of some help.

**Comment by bagustris** [comment]
Thanks @Neclow,

I can reproduce the Colab demo without error. 
Seems there are different configurations on local and Colab.

I got the following error when running `tfds build` (`tensorflow_datasets=4.3.0`) locally, complaining 
about tensorflow (but no error on using Colab):

``` bash
Failed to import TensorFlow. Please note that TensorFlow is not installed by default when you install TFDS.
This allow you to choose to install either `tf-nightly` or `tensorflow`. 
Please install the most recent version of TensorFlow, 
by following the instructions at https://tensorflow.org/install.
```
Then I installed the newest tensorflow, TF2.1

Finally I can solve this issue for `aesdd` by creating new venv using `python3.7` (looking python version on the colab). 
As shown in my first report, the error is related to `json` in `python3.8`.

I also have an error with `emovo` and `ravdess` with the following message:
```
# emovo
$ tfds build
...
    shape1.assert_same_rank(shape2)
  File "/home/bagus/miniconda3/envs/pt1.9-py37/lib/python3.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 1043, in assert_same_rank
    (self, other))
ValueError: Failed to encode example:
{'audio': '/home/bagus/tensorflow_datasets/downloads/extracted/ZIP.emovo.zip/EMOVO/m3/gio-m3-n2.wav', 'label': 'happiness', 'speaker_id': 'm3'}
In <Audio> with name "audio":
Error for /home/bagus/tensorflow_datasets/downloads/extracted/ZIP.emovo.zip/EMOVO/m3/gio-m3-n2.wav: Shapes (139264, 2) and (None,) must have the same rank

# ravdess
$ tfds build
...
 File "/home/bagus/miniconda3/envs/pt1.9-py37/lib/python3.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 1043, in assert_same_rank
    (self, other))
ValueError: Failed to encode example:
{'audio': '/home/bagus/tensorflow_datasets/downloads/extracted/ZIP.RAVDESS_Audio_Speech.zip/Actor_05/03-01-02-01-02-02-05.wav', 'label': 'calm', 'speaker_id': '05'}
In <Audio> with name "audio":
Error for /home/bagus/tensorflow_datasets/downloads/extracted/ZIP.RAVDESS_Audio_Speech.zip/Actor_05/03-01-02-01-02-02-05.wav: Shapes (203403, 2) and (None,) must have the same rank
```

I believe this error is related to `tensorflow` version since I use the newest TF2.1 as the default installation via `pip install tensorflow`.

**Comment by Neclow** [comment]
It might be worth comparing your current installation of Tensorflow with the one in Colab?

Currently, Colab uses TF 2.9.2 (cf. the link to the Colab notebook in my previous message).

Otherwise, I do remember having one "faulty" or irregular sample in a dataset, but I can't remember which sample/dataset. 

For your errors, while I'm not sure it's the "prettiest" fix, a solution would be ensure that all samples in a dataset are all mono or stereo (this is what I get from your error messages in EMOVO and RAVDESS. For instance, in RAVDESS, some samples are mono (shape: ```(None,)```), and some are stereo (shape: ```(203403, 2)```).

I've uploaded a quick gist to convert stereo files to mono files in case you need one, but I haven't used in a while so it might be buggy: https://gist.github.com/Neclow/c0c0531137f98ec05deac3740d8a8329.

Hope that helps!

**Comment by bagustris** [comment]
Thanks for providing the clue @Neclow, 

I previously suspect this error since the SUBESCO code contains the suffix "_mono" (in `subesco.py`). I can confirm now the building of all datasets by tfds has success. Some modifications are needed, especially to collect that path and the speaker information after appending "_mono" to the original file names.

**Comment by Neclow** [comment]
Thanks for the comment! Could you please indicate what changes you would make?

I guess the easiest is to:
 * In the README, indicate that the user should ensure that all samples for a given dataset are all mono or stereo, and add the stereo_to_mono in ```SERAB.utils.py``` as an example of how to do that
 * Remove the "_mono" suffix in ```subesco.py``` (maybe confusing)

**Comment by bagustris** [comment]
I will make a PR if you allow it.

The idea is like this:
Download the original dataset as it is --> do some pre-processings --> run SERAB.

It will be easy to reproduce.

**Comment by Neclow** [comment]
Yes please feel free to do a PR!

**Comment by Neclow** [comment]
I'm closing this issue as it has been inactive for over a month. I updated the README with a comment on how to preprocess the audios before using TFDS + added the stereo_to_mono gist in SERAB.utils.
